(function(){function h(a,d){q[a]||(console.warn("[WARNING] `require('strftime')."+a+"` is deprecated and will be removed in version 1.0. Instead, use `"+d+"`."),q[a]=!0)}function p(a,d,i){function m(a,b,f,k){for(var c="",e=null,d=!1,i=a.length,j=!1,g=0;g<i;g++){var h=a.charCodeAt(g);if(d===!0)if(h===45)e="";else if(h===95)e=" ";else if(h===48)e="0";else if(h===58)j=!0;else{switch(h){case 65:c+=f.days[b.getDay()];break;case 66:c+=f.months[b.getMonth()];break;case 67:c+=l(Math.floor(b.getFullYear()/
100),e);break;case 68:c+=m(f.formats.D,b,f,k);break;case 70:c+=m(f.formats.F,b,f,k);break;case 72:c+=l(b.getHours(),e);break;case 73:c+=l(r(b.getHours()),e);break;case 76:c+=Math.floor(k%1E3)>99?Math.floor(k%1E3):Math.floor(k%1E3)>9?"0"+Math.floor(k%1E3):"00"+Math.floor(k%1E3);break;case 77:c+=l(b.getMinutes(),e);break;case 80:c+=b.getHours()<12?f.am:f.pm;break;case 82:c+=m(f.formats.R,b,f,k);break;case 83:c+=l(b.getSeconds(),e);break;case 84:c+=m(f.formats.T,b,f,k);break;case 85:c+=l(s(b,"sunday"),
e);break;case 87:c+=l(s(b,"monday"),e);break;case 88:c+=m(f.formats.X,b,f,k);break;case 89:c+=b.getFullYear();break;case 90:o&&n===0?c+="GMT":(e=b.toString().match(/\((\w+)\)/),c+=e&&e[1]||"");break;case 97:c+=f.shortDays[b.getDay()];break;case 98:c+=f.shortMonths[b.getMonth()];break;case 99:c+=m(f.formats.c,b,f,k);break;case 100:c+=l(b.getDate(),e);break;case 101:c+=l(b.getDate(),e==null?" ":e);break;case 104:c+=f.shortMonths[b.getMonth()];break;case 106:e=new Date(b.getFullYear(),0,1);e=Math.ceil((b.getTime()-
e.getTime())/864E5);c+=e>99?e:e>9?"0"+e:"00"+e;break;case 107:c+=l(b.getHours(),e==null?" ":e);break;case 108:c+=l(r(b.getHours()),e==null?" ":e);break;case 109:c+=l(b.getMonth()+1,e);break;case 110:c+="\n";break;case 111:c+=String(b.getDate())+u(b.getDate());break;case 112:c+=b.getHours()<12?f.AM:f.PM;break;case 114:c+=m(f.formats.r,b,f,k);break;case 115:c+=Math.floor(k/1E3);break;case 116:c+="\t";break;case 117:e=b.getDay();c+=e===0?7:e;break;case 118:c+=m(f.formats.v,b,f,k);break;case 119:c+=b.getDay();
break;case 120:c+=m(f.formats.x,b,f,k);break;case 121:c+=(""+b.getFullYear()).slice(2);break;case 122:o&&n===0?c+=j?"+00:00":"+0000":(e=n!==0?n/6E4:-b.getTimezoneOffset(),d=j?":":"",h=Math.abs(e%60),c+=(e<0?"-":"+")+l(Math.floor(Math.abs(e/60)))+d+l(h));break;default:c+=a[g]}e=null;d=!1}else h===37?d=!0:c+=a[g]}return c}var j=a||t,n=d||0,o=i||!1,g=0,h,a=function(a,b){var f;if(b)f=b.getTime(),o&&(b=new Date(b.getTime()+(b.getTimezoneOffset()||0)*6E4+n));else{var d=Date.now();d>g&&(g=d,h=new Date(g),
f=g,o&&(h=new Date(g+(h.getTimezoneOffset()||0)*6E4+n)));b=h}return m(a,b,j,f)};a.localize=function(a){return new p(a||j,n,o)};a.timezone=function(a){var b=n,f=o,d=typeof a;if(d==="number"||d==="string")f=!0,d==="string"?(b=a[0]==="-"?-1:1,d=parseInt(a.slice(1,3),10),a=parseInt(a.slice(3,5),10),b=b*(60*d+a)*6E4):d==="number"&&(b=a*6E4);return new p(j,b,f)};a.utc=function(){return new p(j,n,!0)};return a}function l(a,d){if(d===""||a>9)return a;d==null&&(d="0");return d+a}function r(a){if(a===0)return 12;
else if(a>12)return a-12;return a}function s(a,d){var d=d||"sunday",i=a.getDay();d==="monday"&&(i===0?i=6:i--);var h=new Date(a.getFullYear(),0,1);return Math.floor(((a-h)/864E5+7-i)/7)}function u(a){var d=a%10;a%=100;if(a>=11&&a<=13||d===0||d>=4)return"th";switch(d){case 1:return"st";case 2:return"nd";case 3:return"rd"}}var g,t={days:["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"],shortDays:["Sun","Mon","Tue","Wed","Thu","Fri","Sat"],months:["January","February","March",
"April","May","June","July","August","September","October","November","December"],shortMonths:["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],AM:"AM",PM:"PM",am:"am",pm:"pm",formats:{D:"%m/%d/%y",F:"%Y-%m-%d",R:"%H:%M",T:"%H:%M:%S",X:"%T",c:"%a %b %d %X %Y",r:"%I:%M:%S %p",v:"%e-%b-%Y",x:"%D"}},j=new p(t,0,!1);g=typeof module!=="undefined"?module.exports=j:function(){return this||(0,eval)("this")}();var q={};g.strftime=function(a,d,i){h("strftime","require('strftime')(format, date)` or `require('strftime').localize(locale)(format, date)");
return(i?j.localize(i):j)(a,d)};g.strftimeTZ=function(a,d,i,g){h("strftimeTZ","require('strftime').timezone(tz)(format, date)` or `require('strftime').timezone(tz).localize(locale)(format, date)");if((typeof i=="number"||typeof i=="string")&&g==null)g=i,i=void 0;return(i?j.localize(i):j).timezone(g)(a,d)};g.strftimeUTC=function(a,d,g){h("strftimeUTC","require('strftime').utc()(format, date)` or `require('strftime').localize(locale).utc()(format, date)");return(g?j.localize(g):j).utc()(a,d)};g.localizedStrftime=
function(a){h("localizedStrftime","require('strftime').localize(locale)");return j.localize(a)}})();
